config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :order_items
  get 'cart', to: 'cart#show'
  get 'search', to: 'menu#search'
  get 'users', to: 'admin#users_list'
  resources :categories
  get 'menu', to: 'menu#index'
  devise_for :users
  resources :reviews
  resources :products
  root 'pages#home'
  get 'info', to: 'pages#info'
  get 'admin', to: 'admin#index'
  get 'user', to: 'users#index'
  resources :orders
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
  post 'cart/checkout', to: 'menu#index'
  get :send_order_mail, to: 'cart#send_order_mail', as: :send_order_mail
  get :send_payment_reminder, to: 'order#send_payment_reminder', as: :send_payment_reminder
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items, dependent: :destroy
	before_save :set_subtotal


	def subtotal
		order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price + order_item.priceDiff)* order_item.quantity  : 0}.sum
	end

	private
	def set_subtotal
		self[:subtotal] = subtotal
	end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
  	if persisted?
  		self[:unit_price]
  	else
  		product.price
  	end
  end

  def total
  	return (unit_price + priceDiff) * quantity
  end

  private
  def set_unit_price
  	self[:unit_price] = unit_price
  end

  def set_total
  	self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	has_one_attached :image
	has_many :order_items, dependent: :destroy
	has_many :reviews
	before_save :remove_blank_sizes

	def remove_blank_sizes
	  sizes.reject!(&:blank?)
	  priceDiff.reject!(&:blank?)
	end
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :product, required: false

end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	delegate :subtotal, to: :order

	def show
	  	@page = 'cart';
	  	@order = current_order
	  	@first_name = current_order.first_name
	  	if current_order.nil?
	  		@order_items = nil
	  	else	  	
	  		@order_items = current_order.order_items
	  	end
  	end

  	def send_order_mail
	  @order = Order.last
	  @user = current_user

	  OrderMailer.new_order(@order, @user).deliver
	  flash[:success] = "Order Confirmed."
	  redirect_to menu_path
	end

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
	before_action :set_cats
  def index
  	@page = 'menu';
  	@products = Product.all
    @order_item = current_order.order_items.new
  end

  def search
  	query = params[:search]

  	results = Product.where('name', "%#{query}%")
  	if params[:filter] == 'Select Filter'
  		@products = results
  	else
  		symbol = params[:filter].gsub(/ /, '_').downcase.to_sym
  		@prodcuts = results.where(symbol: true)
  	end

    respond_to do |format|
      format.js
    end
  end



  private

  def set_cats
  	@cats = Category.all.where(display: true)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def current_order
	    # Use Find by id to avoid potential erros
	    if Order.find_by_id(session[:order_id]).nil?
	      Order.new
	    else
	      Order.find_by_id(session[:order_id])
	    end
	end
	
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="admin-table">  

  <h1> Admin Page </h1>

  <table class="table stripped-rows">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Feature</th>
        <th scope="col">View</th>
        <th scope="col">Add New</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>Products</td>
        <td><%= link_to 'View Products', products_path %></td>
        <td><%= link_to 'New Product', new_product_path %></td>
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>Categories</td>
        <td><%= link_to 'View Categories', categories_path %></td>
        <td><%= link_to 'New Category', new_category_path %></td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>Users</td>
        <td><%= link_to 'View Users', users_path %></td>
      </tr>
      <tr>
        <th scope="row">4</th>
        <td>Orders Received</td>
        <td><%= link_to 'View Orders', orders_path %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/users_list.html.erb
<% if current_user.admin? %>
<table class = "table">
    <thead>
        <tr>
          <th>Name</th>
          <th>Email ID</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
  	        <tr>
  	            <td><%= user.first_name %> <%=user.last_name %></td>
  	            <td><%= user.email %></td>
  	        </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

app/views/layouts/_links.html.erb
<div class = "col-2">
	<h5 class="link-container">
		<%= link_to "Home", root_path, class:"link #{@page == 'home' ? 'active' : ''}" %>
	</h5>

	<h5 class="link-container">
		<%= link_to "Menu", menu_path, class:"link #{@page == 'menu' ? 'active' : ''}" %>
	</h5>

	<h5 class="link-container">
		<%= link_to "Cart", cart_path, class:"link #{@page == 'cart' ? 'active' : ''}" %>
	</h5>

	<h5 class="link-container">
		<%= link_to "Reviews", reviews_path, class:"link #{@page == 'reviews' ? 'active' : ''}" %>
	</h5>

	<% if user_signed_in? && !current_user.admin? %>
		<h5 class="link-container">
			<%= link_to "User Profile", user_path, class:"link #{@page == 'user' ? 'active' : ''}" %>
		</h5>
	<%end%>

	<% if user_signed_in? && current_user.admin? %>
		<h5 class="link-container">
			<%= link_to "Admin Dashboard", admin_path, class:"link #{@page == 'admin' ? 'active' : ''}" %>
		</h5>
	<%end%>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark" style="background-color: #d63384;">
  <a class="navbar-brand" href="#">
    <img src="/logo.jpg" alt="" width="60" height="50" class="rounded mx-auto d-block" >
    <%= link_to "Shadow's Cakes", root_path, class: "navbar-brand" %>
  </a>
   
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse"></div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
          <%= link_to "Menu", menu_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
          <%= link_to "Reviews", reviews_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? && !current_user.admin? %>
        <li class="nav-item">
            <%= link_to "User Profile", user_path, class:"nav-link" %>
        </li>
      <%end%>

      <% if user_signed_in? && current_user.admin? %>
        <li class="nav-item">
          <%= link_to "Admin Dashboard", admin_path, class:"nav-link" %>
        </li>
      <%end%>
    </ul>

    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
      <%else%>

        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, class:"nav-link" %>
        </li>
      <%end%>

      <li class="nav-item">
        <a class="navbar-brand" href="http://localhost:3000/cart">
        <%= image_tag("cart.png", size: "30x30") %>
      </a>
      </li>
    </ul>
  </div>
</nav>

<script>
  $(document).ready(function() { $(".dropdown-toggle").dropdown(); })
</script>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <!-- font-family: 'Alegreya', serif;
    font-family: 'Playfair Display', serif;
    font-family: 'Libre Baskerville', serif; -->
    <link href="//cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link href="assets/bootstrap.min.css" rel="stylesheet">
    
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"> </script>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="//fonts.googleapis.com/css2?family=Open+Sans&family=Roboto&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="//fonts.googleapis.com/css2?family=Orelega+One&family=Roboto&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="//fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="//fonts.googleapis.com/css2?family=Libre+Baskerville&family=Lora&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="//fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="//fonts.googleapis.com/css2?family=Alegreya&family=Playfair+Display&display=swap" rel="stylesheet">


    <title>ShadowCakes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% cache do %>
        <%= render 'layouts/navbar' %>
        <div class = "<%= @page %>-page">
            <div class="row page-container">
                <div class="col-2"> </div>
                <div class = "col-8">
                    <% unless @page == "home" %>
                    <%= render 'layouts/title' %>
                    <% end %>
                    <br/>
                    <p class="alert"><%= alert %></p>
                    <%= yield %>
                </div>
                <div class="col-2"> </div>
            </div>
        </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="col-8">
	<img src="logo.jpg" width="1000" height="500">
</div>

app/views/pages/info.html.erb
<div class = "info-container">

	<h1>Pages#info</h1>
	<p> Please note we are pick up onyl. We are located at Kerrisdale. </p>

</div>