config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :order_items
  get 'cart', to: 'cart#show'
  get 'search', to: 'menu#search'
  get 'users', to: 'admin#users_list'
  resources :categories
  get 'menu', to: 'menu#index'
  devise_for :users
  resources :reviews
  resources :products
  root 'pages#home'
  get 'info', to: 'pages#info'
  get 'admin', to: 'admin#index'
  get 'user', to: 'users#index'
  resources :orders
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
  post 'cart/checkout', to: 'menu#index'
  get :send_order_mail, to: 'cart#send_order_mail', as: :send_order_mail
  get :send_payment_reminder, to: 'order#send_payment_reminder', as: :send_payment_reminder
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items, dependent: :destroy
	before_save :set_subtotal


	def subtotal
		order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price + order_item.priceDiff)* order_item.quantity  : 0}.sum
	end

	private
	def set_subtotal
		self[:subtotal] = subtotal
	end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
  	if persisted?
  		self[:unit_price]
  	else
  		product.price
  	end
  end

  def total
  	return (unit_price + priceDiff) * quantity
  end

  private
  def set_unit_price
  	self[:unit_price] = unit_price
  end

  def set_total
  	self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	has_one_attached :image
	has_many :order_items, dependent: :destroy
	has_many :reviews
	before_save :remove_blank_sizes

	def remove_blank_sizes
	  sizes.reject!(&:blank?)
	  priceDiff.reject!(&:blank?)
	end
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :product, required: false

end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	def index
		@page = 'admin';
	end

	def users_list
		@users = User.all
	end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	delegate :subtotal, to: :order

	def show
	  	@page = 'cart';
	  	@order = current_order
	  	@first_name = current_order.first_name
	  	if current_order.nil?
	  		@order_items = nil
	  	else	  	
	  		@order_items = current_order.order_items
	  	end
  	end

  	def send_order_mail
	  @order = Order.last
	  @user = current_user

	  OrderMailer.new_order(@order, @user).deliver
	  flash[:success] = "Order Confirmed."
	  redirect_to menu_path
	end

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
	before_action :set_cats
  def index
  	@page = 'menu';
  	@products = Product.all
    @order_item = current_order.order_items.new
  end

  def search
  	query = params[:search]

  	results = Product.where('name', "%#{query}%")
  	if params[:filter] == 'Select Filter'
  		@products = results
  	else
  		symbol = params[:filter].gsub(/ /, '_').downcase.to_sym
  		@prodcuts = results.where(symbol: true)
  	end

    respond_to do |format|
      format.js
    end
  end



  private

  def set_cats
  	@cats = Category.all.where(display: true)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@page = 'home'
  end

  def info
  	@page = 'info'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  respond_to :html, :xml, :json

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
    @page = 'products'
    if @product.reviews.blank?
      @average_review = "N/A"
    else
      @average_review = @product.reviews.average(:rating).round(2)
    end
    @order_item = current_order.order_items.new
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.category = Category.find(1)
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product.category = Category.find(params[:product][:category_id])
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product.category = Category.find(params[:product][:category_id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:sold_out, :name, :description, :price, :image, :category_id, :gluten_free, :dairy_free, :contains_peanuts, :featured, { sizes: [] }, :mult_size, {priceDiff: [] }, :feeds)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def current_order
	    # Use Find by id to avoid potential erros
	    if Order.find_by_id(session[:order_id]).nil?
	      Order.new
	    else
	      Order.find_by_id(session[:order_id])
	    end
	end
	
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= simple_form_for @product do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :ingredients %>
    <%= form.text_area :ingredients %>
  </div>

  <div class="field">
    <%= form.label :feeds %>
    <%= form.text_area :feeds %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :gluten_free %>
    <%= form.check_box :gluten_free %>
  </div>

  <div class="field">
    <%= form.label :dairy_free %>
    <%= form.check_box :dairy_free %>
  </div>

  <div class="field">
    <%= form.label :contains_peanuts %>
    <%= form.check_box :contains_peanuts %>
  </div>

  <div class="field">
    <%= form.label :sold_out %>
    <%= form.check_box :sold_out %>
  </div>

  <div class="field">
    <%= form.label :featured %>
    <%= form.check_box :featured %>
  </div>

  <div class = "field">
    <%= form.label :category %>
    <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :heading, @product.category.id) %>
  </div>

  <div class = "field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :mult_size %>
    <%= form.check_box :mult_size %>
  </div>


  <div clas = "field">
    <%= form.label :priceDiff, "Additional Price for different Sizes" %>
    <div id = "price-field">
      <%= form.input :priceDiff, as: :array %>
    </div>
    <div id="addRow"></div>
    <button type="button" class="btn btn-secondary" onclick="addPriceRow()">Add Price Change</button>
  </div>

  <div class = "field">
    <%= form.label :sizes %>
    <div id = "size-field">
      <%= form.input :sizes, as: :array %>
    </div>
    <div id = "dynamic-inputs"></div>
    <button type="button" class="btn btn-secondary" onclick="addSizeRow()">Add Size</button>
  </div>

  <br/><br/>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<script>
  function addSizeRow() {
    $("#dynamic-inputs").append($("#size-field").html());
  }

  function addPriceRow() {
    $("#addRow").append($("#price-field").html());
  }

  function submiForm() {
    let data = []
    $("[name='label']").each((i, item)=>
    {
      data.push({'label': item.value, 'amount':  $("[name='amount']")[i].value})
    })
    console.log({'quote_amounts': data})
    $.ajax({
        url: 'urlOfYourActionController',
        data: {'quote_amounts': data},
        type: 'POST',
        success: function(data){
            // handle your success here
            console.log(data);
        }
    });
  }
</script>

app/views/products/edit.html.erb
<% if user_signed_in? %>
	<% if current_user.admin? %>

		<h1>Editing Product</h1>

		<%= render 'form', product: @product %>

		<%= link_to 'Show', @product %> |
		<%= link_to 'Back', products_path %>

	<%end%>

<% else %>

	<%= NOT AUTHORIZED TO VIEW THIS PAGE %>

<%end%>

app/views/products/index.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>

    <p id="notice"><%= notice %></p>

    <h1>Products</h1>

    <table class = "table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Price</th>
          <th>Gluten free</th>
          <th>Dairy free</th>
          <th>Contains peanuts</th>
          <th>Featured</th>
          <th>Sold Out</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            <td><%= product.price %></td>
            <td><%= product.gluten_free %></td>
            <td><%= product.dairy_free %></td>
            <td><%= product.contains_peanuts %></td>
            <td><%= product.featured %></td>
            <td><%= product.sold_out %></td>
            <td><%= link_to 'Show', product %></td>
            <td><%= link_to 'Edit', edit_product_path(product) %></td>
            <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Product', new_product_path %>


  <%end%>

<% else %>

  <%= NOT AUTHORIZED TO VIEW THIS PAGE %>

<%end%>

app/views/products/new.html.erb
<% if user_signed_in? %>
	<% if current_user.admin? %>
		<h1>New Product</h1>

		<%= render 'form', product: @product %>

		<%= link_to 'Back', products_path %>

	<%end%>

<% else %>

	<%= NOT AUTHORIZED TO VIEW THIS PAGE %>

<%end%>

app/views/products/show.html.erb
<div id="cart">
  <%= render 'cart/cart'%>
</div>

<script>
  function check() {
    if (<%= @product.mult_size %>){
      alert("Prices vary according to size");
      document.getElementById("hidden_price_field").value = ($("#sizeDropdown").prop('selectedIndex'));
      var index = ($("#sizeDropdown").prop('selectedIndex'));
      var arr = new Array(<%= @product.priceDiff.map(&:to_s).join(", ") %>);
      var addCost = arr[index];
      document.getElementById("priceField").innerHTML = "+ $"+ addCost;
      document.getElementById("additionalCost").value = addCost;
      console.log(addCost);
    }
  }
</script>

<div class = "product-container">
  <div class = "left">
    <div class = "product-photo">
      <figure class="figure">
        <img src="/<%= @product.name%>.jpg"  class="img-thumbnail img-fluid img-responsive contain" alt="...">
      </figure>
    </div>
  </div>

  <div class = "right">
    <div class = "product-details">
      <h1 itemprop = "name" margin:0px class="product-name"><%=@product.name%> </h1>
      <br/>
      <span class = "product-price"> <%= number_to_currency(@product.price)%> </span>
      <input type="hidden" id="hidden_price_field" >
      <p id="priceField"></p>
      <div class = "product-description" style="width: 400px;">
        <h4 class="product-description-text"> <%= @product.description %> </h4>
      </div>
      <br/>
      <div class = "product-average-review" >
        <h6 class="product-average-review-text"> Average Rating : <%= @average_review %> </h6>
      </div>
    </div>
    <br/>
    <div class = "cart-info">
      <% if @product.sold_out == false %>
        <%= form_for @order_item, class:"form-group", remote: true  do |f|%>
          <% if @product.mult_size %>
              <%= f.label :diffSize, "Select Your Size" %>
              <%= f.select :diffSize, @product.sizes, {}, prompt: 'Select Your Size', class:'form-select', id: "sizeDropdown", onchange: "check()" %>
          <%end%>
          <%= f.hidden_field :product_id, value: @product.id %>
          <%= f.hidden_field :priceDiff, id: "additionalCost" %>
          <%= f.label :diffSize, "Quantity" %>
          <%= f.number_field :quantity, prompt: "Quantity", class:"form-control", value: 1, min: 1%>
          <br/>
          <%= f.submit "Add to Cart", class:'btn btn-primary', id:"addToCart", remote: true %>
        <% end %>
      <% else %>
        <%= link_to "Sold Out", "", class:'btn btn-secondary' %>
      <% end %>
    </div>
  </div>


  <div class = "product-dropdown">
    <div class="accordion" id="product-dropdown">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            <strong>Ingredients</strong>
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <%if @product.ingredients.nil? %>
              <p> Ingredients go here </p>
            <%else%>
              <p><%= @product.ingredients %></p>
            <%end%>
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingTwo">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
           <strong>Portion Size</strong>
          </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <%= @product.feeds%>
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingThree">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
           <strong>Dietary Restrictions</strong>
          </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <p>
              <% if @product.gluten_free %>
                Gluten Free!
              <% else %>
                Contains Gluten.
              <%end%>
            </p>

            <p>
              <% if @product.dairy_free %>
                Dairy Free!
              <% else %>
                Contains Dairy.
              <%end%>
            </p>

            <p>
              <% if @product.contains_peanuts %>
                Contains peanuts.
              <% else %>
                Peanut Free!
              <%end%>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>



  <div class = 'product-review-container'>
    <h2 class="review-title"> Product Reviews </h2>

    <%= render @product.reviews %>

    <%= link_to "Add Review", new_review_path %>
  </div>
</div>

<br/>

<%= link_to 'Back to Menu', menu_path, class:"btn btn-secondary" %>

<script>
   $("#addToCart").click(function() {
      alert("The item has been added to your cart.");
      @displayAlert = true;
   });
</script>